backend:
  name: github
  repo: markzhdan/mark-zhdan-website
  branch: master
media_folder: "images/uploads"
media_library:
  name: uploads
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/dailyblogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{month}}-{{day}}-{{year}}" # Filename template, e.g., MM-DD-YYYY.md
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Coding Summary", name: "summary", widget: "markdown" }
      - { label: "Learnings", name: "learnings", widget: "markdown" }
      - { label: "Goals", name: "goals", widget: "markdown" }
      - { label: "Cool Snippet", name: "snippet", widget: "markdown" }
      - { label: "Other", name: "other", widget: "markdown" }
